//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsMax
    {
        public decimal Price { get; set; }
        public string Number { get; set; }
        public int AutoserviceId { get; set; }
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Photo { get; set; }
        public int RoleId { get; set; }
    
        public virtual AutoserviceMax AutoserviceMax { get; set; }
        public virtual RoleMax RoleMax { get; set; }
    }
}
