//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Max
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class autoservice_kpEntities6 : DbContext
    {
        public autoservice_kpEntities6()
            : base("name=autoservice_kpEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoserviceMax> AutoserviceMax { get; set; }
        public virtual DbSet<ContractsMax> ContractsMax { get; set; }
        public virtual DbSet<RoleMax> RoleMax { get; set; }
    }
}
